apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: create-project
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: projects/create-project
    repoURL: https://github.com/iam-veeramalla/my-gitops-examples
    targetRevision: HEAD
