apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: foo-green

bases:
- ../../base
patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: foo
    path: foo-deployment.yaml
  - target:
      version: v1
      group: route.openshift.io
      kind: Route
      name: foo
    path: foo-route.yaml
resources:
- foo-namespace.yaml
