apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bgd-green

bases:
- ../../base
patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: bgd
    path: bgd-deployment.yaml
  - target:
      version: v1
      group: networking.k8s.io
      kind: Ingress
      name: bgd-ingress
    path: bgd-ing.yaml
resources:
- bgd-namespace.yaml
