apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: foo
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      # v0.2.0+ form - does not require cluster/URL keys (but are still supported)
      - overlay: blue
        gitRepo: https://github.com/iam-veeramalla/my-gitops-examples
        appPath: applicationsets/list-generator/v0.2/ocp/overlays
        appBranch: master
      - overlay: green
        gitRepo: https://github.com/iam-veeramalla/my-gitops-examples
        appPath: applicationsets/list-generator/v0.2/ocp/overlays
        appBranch: main
  template:
    metadata:
      name: 'foo-{{overlay}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: '{{gitRepo}}'
        targetRevision: '{{appBranch}}'
        path: '{{appPath}}/{{overlay}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'foo-{{overlay}}'
